<Project>
  <Import Project="../Directory.Build.props" />

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsPublishable>false</IsPublishable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="TUnit" />
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="Moq" />
    <PackageReference Include="Bogus" />
    <PackageReference Include="AutoFixture" />
    <PackageReference Include="AutoFixture.AutoMoq" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="TUnit" />
    <Using Include="Moq" />
    <Using Include="FluentAssertions" />
    <Using Include="Bogus" />
    <Using Include="AutoFixture" />
    <Using Include="AutoFixture.Kernel" />
    <Using Include="AutoFixture.AutoMoq" />
    <Using Include="$(ProjectName).Fixtures" />
  </ItemGroup>

  <!-- NOTE: disabling TUnit warnings here because native AOT -->
  <PropertyGroup>
    <!-- Return a `Func<T>` rather than a `<T>`. -->
    <NoWarn>$(NoWarn);TUnit0046</NoWarn>
  </PropertyGroup>
</Project>
