<Project>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>13</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <!-- <RequiresAspNetWebAssets>true</RequiresAspNetWebAssets> -->
  </PropertyGroup>

  <PropertyGroup>
    <NoDefaultLaunchSettingsFile>true</NoDefaultLaunchSettingsFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference
        Include="StyleCop.Analyzers"
        Condition="$(MSBuildProjectExtension) == '.csproj'">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>

    <PackageReference
        Include="SonarAnalyzer.CSharp"
        Condition="$(MSBuildProjectExtension) == '.csproj'">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Assets/**/*" />
  </ItemGroup>

</Project>
