<Project>

  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
    <CentralPackageVersionOverrideEnabled>false</CentralPackageVersionOverrideEnabled>
  </PropertyGroup>

  <PropertyGroup>
    <EntityFrameworkCoreVersion>8.0.3</EntityFrameworkCoreVersion>
    <QuartzVersion>3.13.0</QuartzVersion>
    <MassTransitVersion>8.2.2</MassTransitVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageVersion Include="Altibiz.DependencyInjection.Extensions" Version="1.0.10" />

    <PackageVersion Include="CsvHelper" Version="31.0.3" />
    <PackageVersion Include="Tomlyn" Version="0.19.0" />
    <PackageVersion Include="HtmlSanitizer" Version="9.0.876" />

    <PackageVersion Include="System.Linq.Async" Version="6.0.1" />

    <PackageVersion Include="MailKit" Version="4.7.1.1" />

    <PackageVersion Include="CommandLineParser" Version="2.9.1" />

    <PackageVersion Include="OpenAI" Version="2.1.0" />

    <PackageVersion Include="Microsoft.Playwright" Version="1.50.0" />

    <PackageVersion Include="Npgsql" Version="8.0.3" />
    <PackageVersion Include="Dapper" Version="2.1.35" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Design" Version="$(EntityFrameworkCoreVersion)" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Proxies" Version="$(EntityFrameworkCoreVersion)" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.InMemory" Version="$(EntityFrameworkCoreVersion)" />
    <PackageVersion Include="EFCore.NamingConventions" Version="$(EntityFrameworkCoreVersion)" />
    <PackageVersion Include="EFCore.BulkExtensions" Version="$(EntityFrameworkCoreVersion)" />
    <PackageVersion Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.4" />
    <PackageVersion Include="Z.EntityFramework.Plus.EFCore" Version="8.101.2" />

    <PackageVersion Include="Quartz" Version="$(QuartzVersion)" />
    <PackageVersion Include="Quartz.Serialization.SystemTextJson" Version="$(QuartzVersion)" />
    <PackageVersion Include="Quartz.Extensions.DependencyInjection" Version="$(QuartzVersion)" />
    <PackageVersion Include="Quartz.Extensions.Hosting" Version="$(QuartzVersion)" />
    <PackageVersion Include="AppAny.Quartz.EntityFrameworkCore.Migrations.PostgreSQL" Version="0.5.1" />

    <PackageVersion Include="MassTransit" Version="$(MassTransitVersion)" />
    <PackageVersion Include="MassTransit.RabbitMQ" Version="$(MassTransitVersion)" />
    <PackageVersion Include="MassTransit.Azure.ServiceBus.Core" Version="$(MassTransitVersion)" />
    <PackageVersion Include="MassTransit.EntityFrameworkCore" Version="$(MassTransitVersion)" />

    <PackageVersion Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" Version="8.0.17" />
    <PackageVersion Include="Microsoft.AspNetCore.Authentication.Cookies" Version="2.3.0" />
    <PackageVersion Include="Novell.Directory.Ldap.NETStandard" Version="3.6.0" />

    <PackageVersion Include="MudBlazor" Version="8.1.0" />
    <PackageVersion Include="MudBlazor.ThemeManager" Version="3.0.0" />
    <PackageVersion Include="Blazor-ApexCharts" Version="5.0.1" />
    <PackageVersion Include="Blazored.LocalStorage" Version="4.5.0" />
    <PackageVersion Include="Tizzani.MudBlazor.HtmlEditor" Version="2.3.0" />

    <PackageVersion Include="TUnit" Version="0.25.21" />
    <PackageVersion Include="FluentAssertions" Version="6.12.0" />
    <PackageVersion Include="Moq" Version="4.20.70" />
    <PackageVersion Include="Bogus" Version="35.5.1" />
    <PackageVersion Include="AutoFixture" Version="4.18.1" />
    <PackageVersion Include="AutoFixture.AutoMoq" Version="4.18.1" />
    <PackageVersion Include="Testcontainers" Version="4.5.0" />
    <PackageVersion Include="Microsoft.AspNetCore.Mvc.Testing" Version="8.0.17" />
    <PackageVersion Include="BCrypt.Net-Next" Version="4.0.3" />

    <PackageVersion Include="Swashbuckle.AspNetCore" Version="9.0.6" />
    <PackageVersion Include="Asp.Versioning.Mvc" Version="8.1.0" />
    <PackageVersion Include="Asp.Versioning.Mvc.ApiExplorer" Version="8.1.0" />

    <PackageVersion Include="System.Runtime.Caching" Version="9.0.10" />

    <PackageVersion Include="StyleCop.Analyzers" Version="1.1.118" />
    <PackageVersion Include="SonarAnalyzer.CSharp" Version="9.28.0.94264" />
  </ItemGroup>

</Project>
