# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json

x-ollama-common: &ollama-common
  image: ollama/ollama:0.6.3
  restart: always
  ports:
    - 11434:11434
  volumes:
    - ollama_data:/root/.ollama
  networks:
    - ozds-network
  healthcheck:
    test: curl --fail http://localhost:11434 || exit 1
    interval: 30s
    timeout: 10s
    retries: 5

services:
  postgres:
    image: timescale/timescaledb-ha:pg14-latest
    restart: always
    volumes:
      - postgres_data:/home/postgres/pgdata/data
    networks:
      - ozds-network
    environment:
      POSTGRES_DB: ozds
      POSTGRES_USER: ozds
      POSTGRES_PASSWORD: ozds
    ports:
      - 5432:5432
    healthcheck:
      test: pg_isready -d ozds -U ozds
      interval: 1m
      timeout: 10s
      retries: 10

  rabbitmq:
    image: rabbitmq:3.13-management
    restart: always
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - ozds-network
    environment:
      RABBITMQ_DEFAULT_USER: ozds
      RABBITMQ_DEFAULT_PASS: ozds
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: rabbitmqctl node_health_check
      interval: 1m
      timeout: 10s
      retries: 10

  mailserver:
    image: axllent/mailpit:v1.26
    restart: always
    ports:
      - 1025:1025
      - 8025:8025
    environment:
      MP_DATABASE: /data/mailpit.db
      MP_UI_AUTH: "ozds:ozds"
      MP_SEND_API_AUTH: "ozds:ozds"
      MP_SMTP_AUTH: "ozds:ozds"
      MP_SMTP_AUTH_ALLOW_INSECURE: "true"
    volumes:
      - mailserver_data:/data
    networks:
      - ozds-network
    healthcheck:
      test: curl --fail -u ozds:ozds http://localhost:8025 || exit 1
      interval: 30s
      timeout: 10s
      retries: 5

  auth:
    image: authelia/authelia:4.39.4
    restart: always
    depends_on: [ldap]
    ports:
      - 9091:9091
    volumes:
      - ./scripts/auth/configuration.yml:/config/configuration.yml
      - ./scripts/auth/users.yml:/config/users.yml
    networks:
      - ozds-network
    healthcheck:
      test: curl --fail http://localhost:9091 || exit 1
      interval: 30s
      timeout: 10s
      retries: 5

  ldap:
    image: lldap/lldap:2025-05-19
    restart: always
    ports:
      - 3890:3890
      - 17170:17170
    volumes:
      - ./scripts/ldap/users.db:/data/users.db
      - ./scripts/ldap/lldap_config.toml:/data/lldap_config.toml
    networks:
      - ozds-network
    healthcheck:
      test: curl --fail http://localhost:17170 || exit 1
      interval: 30s
      timeout: 10s
      retries: 5

  ollama-cpu:
    <<: *ollama-common
    profiles: [cpu]

  ollama-cuda:
    <<: *ollama-common
    profiles: [cuda]
    deploy:
      resources:
        reservations:
          devices:
            - driver: cdi
              capabilities: [gpu]
              device_ids:
                - nvidia.com/gpu=all

volumes:
  postgres_data:
    driver: local
  rabbitmq_data:
    driver: local
  mailserver_data:
    driver: local
  ollama_data:
    driver: local

networks:
  ozds-network:
    name: ozds-network
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: ozdsbr
