# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json

services:
  postgres:
    image: timescale/timescaledb-ha:pg14-latest
    restart: always
    volumes:
      - postgres_data:/home/postgres/pgdata/data
    environment:
      - POSTGRES_DB=ozds
      - POSTGRES_USER=ozds
      - POSTGRES_PASSWORD=ozds
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ozds -U ozds"]
      interval: 1m
      timeout: 10s
      retries: 10
  rabbitmq:
    image: rabbitmq:3.13-management
    restart: always
    profiles: [all]
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=ozds
      - RABBITMQ_DEFAULT_PASS=ozds
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: ["CMD-SHELL", "rabbitmqctl node_health_check"]
      interval: 1m
      timeout: 10s
      retries: 10

volumes:
  postgres_data:
    driver: local
  rabbitmq_data:
    driver: local
