[book]
authors = [
  "Hrvoje Jurić <hrvoje@altibiz.com>",
  "Gabrijel Čmelić <gabrijel@altibiz.com>",
]
language = "en"
multilingual = false
src = "src"
title = "ozds"

[preprocessor.plantuml]
plantuml-cmd = "plantuml"
