# NOTE: ASP.NET core stores large amounts of data in cookies
server:
  buffers:
    read: 8192
    write: 8192

authentication_backend:
  ldap:
    implementation: lldap
    address: ldap://ldap:3890
    base_dn: dc=altibiz,dc=com
    user: uid=admin,ou=people,dc=altibiz,dc=com
    password: "admin-ozds"
    additional_users_dn: ou=people

access_control:
  default_policy: "one_factor"
  rules:
    - domain: "127.0.0.1"
      policy: "one_factor"
    - domain: "localhost"
      policy: "one_factor"

session:
  secret: "authelia-needs-20-characters-at-least-for-these-secrets"
  cookies:
    - domain: "127.0.0.1"
      authelia_url: "https://127.0.0.1:9091"
      default_redirection_url: "https://127.0.0.1:5001"

identity_validation:
  reset_password:
    jwt_secret: "authelia-needs-20-characters-at-least-for-these-secrets"
    jwt_algorithm: "HS256"

storage:
  encryption_key: "authelia-needs-20-characters-at-least-for-these-secrets"
  local:
    path: "/app/db.sqlite3"

notifier:
  disable_startup_check: false
  filesystem:
    filename: "/app/notification.txt"

identity_providers:
  oidc:
    hmac_secret: "authelianeedsasupersupermegagigaultrasafesecretforthisonethatislikeatleast64characterslong"
    jwks:
      - key_id: ozds
        algorithm: RS256
        use: sig
        key: |
          -----BEGIN PRIVATE KEY-----
          MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC5Ll1SI7RP+wKh
          Zx5TVSehpFeYCG4YYB+1UqELGEaDXQdOgZkPwrU9qLVe96O/7F1oIH+pIFxUfcRH
          VI563GS05X7HdQXeqsw8oLGGOcXKIMpHhll3ajt8rk97ga4zNkcOPGFsp6Ye6OCW
          dSd9vpJQLl4C7FFf534J8FIIlf6ytzSH9R80qFQMjo3IafU+NrG68BWqkZX1e7Pj
          BVjBusrOa3t1ycYweBd7KAN0YUajb8l4JvYuQfWawCPyXfBS9mBKOyT183iXJEp5
          5dpfw5hcBZ34AbN0Eogyd6Q6MM4hpuxANG303B9FwqR8pDtbEWKEVCCCIIyA45rR
          8WdK6TpRAgMBAAECggEAAvaOS7gtNHJscloMuYH3+7V+KVKeiwlOuJS1OvuNH/ZR
          yEcj7y/1vSIr9Mm69wvjMBKvuEG/oyJ4DOQk0NZ3ThBgskmvFFxgnupmAiMpL7jN
          Q85kiW1LvQz/p0GbS0/SXJSewnb+835VHv3flJAuFdZdbr01TXbjehPnBs16S9sX
          pjHvtFQZ6QbmMTkudhVS6Eg0LP9IeQzYJ9NDu4143MnCA4+h3pUV6GVI9VCBT5l2
          Kw+rK3fY/3XW8oXM85pItbLNVPm3rQGpNxvOEfAYLK/A1Efx/Yra0GjK25AX257n
          8TLDoB6tUldUJwAvW+1OIkcxqf4qFVjIKeP/wT8e+QKBgQDcC9rGqjMFm7VHAshu
          FJis/9BTKQkD7j/4NEq1qIFNdAIW0ArsEM1l3NXMQuMO25Geen2funSi623wOQ8a
          vShQTUjROyeGApXROo/ZgypBJ3QHpIxBW34ZrpW6zRvVRyzr/JPNFeRbEzcJImQh
          BCaZnQBtvMDuBetMoM1EOQnhVwKBgQDXcCkuKYJEkDlTHF1qDDZuxmhlSN36l8GK
          sfZ5Er8Ayed9EBrxWBHBXmVqJjtW1vo3jrVTFSkpMNNSuE/GwhiGJW1GRqpDSdrp
          B216Af2QoHy2DZ1AlVzZIYRZTxE1I7BNYWZ9VtaKLIcXnD45jzpaVnvpKf4dirU1
          8Pq5JLMwlwKBgF3paUuUZAYmuC1AUM46WBatbvmu77wPuJlzp9bzvYuS0TlvPNoX
          KbIpl81/VmyG5RUf7fF3oEPP+rGliH6+8C+lbEhv2KRnAg2z0qTgR+5aqjiAz6Mt
          KxpG2nxJAXH62H824tWKXFVKVBi/5r/4h4jT6tTq0+RB/nRLxI8zULYtAoGBAJ0g
          CojGcWH8JjL9fwv3OEP2pPEqAevgfqHfRbnr+C5lE1ZdRqk66Eg1xpVyqNifFgMr
          LAgaaNjH6XhtQJHfwe8koNwecdN9rBFE/416oiq3Qf2tVEFkLkGWdmaEijJNgyoM
          nalQikxgSW7o32EvmwmEBf96RwHYxm0/Aj3CDIalAoGASzh4NR0YUwToERI4NwaQ
          UcHOyviisYH6ETaI3cfiRNWOD/+wucY58yEYy6kZp/ZBguhA9+h8Or3zPgooo7zI
          z9t3UegUKvuxEEU+MSpT1qJT+hxEZouVTBayaFwwEkPcIJrXZD1Mdfp4U6h4vbKi
          unq0cZDCBt2TcTbff5YfJfo=
          -----END PRIVATE KEY-----
        certificate_chain: |
          -----BEGIN CERTIFICATE-----
          MIIDBzCCAe+gAwIBAgIUPxN7+w5djM+v4PAZGqodLez+OjowDQYJKoZIhvcNAQEL
          BQAwEzERMA8GA1UEAwwIYXV0aGVsaWEwHhcNMjYwNzI4MTAyOTEzWhcNMzYwNzI1
          MTAyOTEzWjATMREwDwYDVQQDDAhhdXRoZWxpYTCCASIwDQYJKoZIhvcNAQEBBQAD
          ggEPADCCAQoCggEBALkuXVIjtE/7AqFnHlNVJ6GkV5gIbhhgH7VSoQsYRoNdB06B
          mQ/CtT2otV73o7/sXWggf6kgXFR9xEdUjnrcZLTlfsd1Bd6qzDygsYY5xcogykeG
          WXdqO3yuT3uBrjM2Rw48YWynph7o4JZ1J32+klAuXgLsUV/nfgnwUgiV/rK3NIf1
          HzSoVAyOjchp9T42sbrwFaqRlfV7s+MFWMG6ys5re3XJxjB4F3soA3RhRqNvyXgm
          9i5B9ZrAI/Jd8FL2YEo7JPXzeJckSnnl2l/DmFwFnfgBs3QSiDJ3pDowziGm7EA0
          bfTcH0XCpHykO1sRYoRUIIIgjIDjmtHxZ0rpOlECAwEAAaNTMFEwHQYDVR0OBBYE
          FOD1y75Gt/Y5NII+FaIjwhxTR5vNMB8GA1UdIwQYMBaAFOD1y75Gt/Y5NII+FaIj
          whxTR5vNMA8GA1UdEwEB/wQFMAMBAf8wDQYJKoZIhvcNAQELBQADggEBAH/BBdAh
          /YFE3qoGF8+CEOJRRTbep6rgpD89ycOnh24Hkn7aB6TmLHuoTxqXmDcUzp+UiL68
          8wP0p6wG6HCcHSvd8+4/iDlAMuPDEkunndG0hJYCxSm+jNDQiOrTQwVLrwrqBPJA
          m2VhwaQ9deaIJ22VN7p+59wy1JsAXuPyfoSlqST9TbrnyWhIVtMfY7Go/5znW+P6
          SXFxklp3NH3yT4aXK8d8bqW3k/zeO+36u7zERcJ/NzR1iN5+OD8kuJEAzmT5fwJc
          /JQ666rPbMXpXwPZ0mVnqwfFxw47WKdl+3Mb2AP15kt+4YVpmNcUBZSrS+wBJQot
          1gRice6h8RRncXI=
          -----END CERTIFICATE-----
    clients:
      - client_id: ozds
        client_name: OZDS
        # Secret is 'ozds'
        client_secret: "$pbkdf2-sha512$310000$a4yy11XswnZybaOYoz4UNw$Lr8mWXBLZEemiQuaZI50/AX.e5dp2ZtdG2JJ/A3d.AMNIkx2UufvxgOGoJH0hhe22B4TNm.sOJuT1f6wlA34gw"
        redirect_uris:
          - https://127.0.0.1:5001/
          - http://127.0.0.1:5000/
          - https://localhost:5001/
          - http://localhost:5000/
          - https://127.0.0.1:5001/signin-oidc
          - http://127.0.0.1:5000/signin-oidc
          - https://localhost:5001/signin-oidc
          - http://localhost:5000/signin-oidc
          - https://127.0.0.1:5001/signout-oidc
          - http://127.0.0.1:5000/signout-oidc
          - https://localhost:5001/signout-oidc
          - http://localhost:5000/signout-oidc
        authorization_policy: one_factor
        token_endpoint_auth_method: client_secret_post
        scopes:
          - openid
          - profile
          - email
          - offline_access
        response_types:
          - code
        grant_types:
          - authorization_code
          - refresh_token
