[language-server]
nil = { command = "nil" }
taplo = { command = "taplo", args = ["lsp", "stdio"] }
yaml-language-server = { command = "yaml-language-server", args = ["--stdio"] }
marksman = { command = "marksman", args = ["server"] }
sqls = { command = "sqls" }
# rzls = { command = "rzls" }

[language-server.omnisharp]
command = "OmniSharp"
args = ["-lsp"]
timeout = 10000

[language-server.vscode-json-language-server]
command = "vscode-json-language-server"
args = ["--stdio"]

[language-server.vscode-json-language-server.config]
provideFormatter = true
format = { enable = true }
json = { validate = { enable = true } }

[language-server.pyright-langserver]
command = "pyright-langserver"
args = ["--stdio"]
config = {}

[[language]]
name = "nix"
auto-format = true
formatter = { command = "nixpkgs-fmt" }
language-servers = ["nil"]

[[language]]
name = "c-sharp"
language-servers = ["omnisharp"]
auto-format = true

[[language]]
name = "python"
auto-format = true
formatter = { command = "yapf" }
language-servers = ["pyright-langserver"]

# [[language]]
# name = "razor"
# scope = "source.razor"
# injection-regex = "razor"
# file-types = ["razor", "cshtml"]
# roots = ["sln", "csproj"]
# # block-comment-tokens = { start = "@*", end = "*@" }
# indent = { tab-width = 2, unit = " " }
# language-servers = ["rzls"]
# auto-format = true

[[language]]
name = "sql"
auto-format = true
formatter = { command = "sql-formatter" }
language-servers = ["sqls"]

[[language]]
name = "yaml"
auto-format = true
formatter = { command = "prettier", args = ["--parser", "yaml"] }
language-servers = ["yaml-language-server"]

[[language]]
name = "json"
auto-format = true
formatter = { command = "prettier", args = ["--parser", "json"] }
language-servers = ["vscode-json-language-server"]

[[language]]
name = "toml"
auto-format = true
language-servers = ["taplo"]

[[language]]
name = "markdown"
auto-format = true
formatter = { command = "prettier", args = ["--parser", "markdown"] }
language-servers = ["marksman"]
