namespace Ozds.Business.Models;

public record AbbMeasurementModel(
  string Source,
  DateTimeOffset Timestamp,
  float VoltageL1_V,
  float VoltageL2_V,
  float VoltageL3_V,
  float CurrentL1_A,
  float CurrentL2_A,
  float CurrentL3_A,
  float ActivePowerL1_W,
  float ActivePowerL2_W,
  float ActivePowerL3_W,
  float ReactivePowerL1_VAR,
  float ReactivePowerL2_VAR,
  float ReactivePowerL3_VAR,
  float ActivePowerImportL1_Wh,
  float ActivePowerImportL2_Wh,
  float ActivePowerImportL3_Wh,
  float ActivePowerExportL1_Wh,
  float ActivePowerExportL2_Wh,
  float ActivePowerExportL3_Wh,
  float ReactivePowerImportL1_VARh,
  float ReactivePowerImportL2_VARh,
  float ReactivePowerImportL3_VARh,
  float ReactivePowerExportL1_VARh,
  float ReactivePowerExportL2_VARh,
  float ReactivePowerExportL3_VARh,
  float ActiveEnergyImportTotal_Wh,
  float ActiveEnergyExportTotal_Wh,
  float ReactiveEnergyImportTotal_VARh,
  float ReactiveEnergyExportTotal_VARh,
  float ActiveEnergyImportTotalT1_Wh,
  float ActiveEnergyImportTotalT2_Wh
);
