namespace Ozds.Business.Models;

public record SchneiderAggregateModel(
  string Source,
  DateTimeOffset Timestamp,
  TimeSpan TimeSpan,
  long AggregateCount,
  float VoltageL1Avg_V,
  float VoltageL2Avg_V,
  float VoltageL3Avg_V,
  float CurrentL1Avg_A,
  float CurrentL2Avg_A,
  float CurrentL3Avg_A,
  float ActivePowerL1Avg_W,
  float ActivePowerL2Avg_W,
  float ActivePowerL3Avg_W,
  float ReactivePowerTotalAvg_VAR,
  float ApparentPowerTotalAvg_VA,
  float ActiveEnergyImportTotalMin_Wh,
  float ActiveEnergyImportTotalMax_Wh,
  float ActiveEnergyImport_Wh,
  float ActivePowerImportAvg_W,
  float ActiveEnergyExportTotalMin_Wh,
  float ActiveEnergyExportTotalMax_Wh,
  float ActiveEnergyExport_Wh,
  float ActivePowerExportAvg_W,
  float ReactiveEnergyImportTotalMin_VARh,
  float ReactiveEnergyImportTotalMax_VARh,
  float ReactiveEnergyImport_VARh,
  float ReactivePowerImportAvg_VAR,
  float ReactiveEnergyExportTotalMin_VARh,
  float ReactiveEnergyExportTotalMax_VARh,
  float ReactiveEnergyExport_VARh,
  float ReactivePowerExportAvg_VAR,
  float ActiveEnergyImportTotalT1Min_Wh,
  float ActiveEnergyImportTotalT1Max_Wh,
  float ActiveEnergyImportT1_Wh,
  float ActivePowerImportT1Avg_W,
  float ActiveEnergyImportTotalT2Min_Wh,
  float ActiveEnergyImportTotalT2Max_Wh,
  float ActiveEnergyImportT2_Wh,
  float ActivePowerImportT2Avg_W
);

