# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: extractions/setup-just@v1
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: actions/setup-dotnet@v3
        with:
          global-json-file: global.json
      - name: ci
        run: just ci

      - name: publish
        run: just publish --property PublishDir=${{env.DOTNET_ROOT}}/myapp

      - name: upload
        uses: actions/upload-artifact@v2
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    steps:
      - name: download
        uses: actions/download-artifact@v2
        with:
          name: .net-app
      - name: deploy
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: "altibiz-mess"
          slot-name: "Production"
          # prettier-ignore
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_4416F6604DF04E9BB6F36F3413BC3CCB }}
          package: .
