# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v25
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: deploy
        shell: nix develop .#deploy -c {0}
        run: |-
          just publish \
            -p PublishDir=${{ env.DOTNET_ROOT }}/myapp

      - name: upload
        uses: actions/upload-artifact@v3
        with:
          name: .net-app
          path: ${{ env.DOTNET_ROOT }}/myapp

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: download
        uses: actions/download-artifact@v3
        with:
          name: .net-app

      - name: deploy
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: "altibiz-mess"
          slot-name: "Production"
          # prettier-ignore
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_012D1E91353344A0A0FFEB89ED713614 }}
          package: .
