# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: format-and-deps

on:
  pull_request:
    branches:
      - dev

jobs:
  format-and-deps:
    name: format-and-deps
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN_HRVOJE }}

      - name: install-nix
        uses: cachix/install-nix-action@v30
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: prepare
        run: nix develop .#check -c dotnet tool restore

      - name: deps
        run: nix develop .#check -c just deps

      - name: format
        run: nix develop .#check -c just format

      - name: commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: format & deps.nix
          branch: ${{ github.head_ref }}
