<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="../../src/Ozds.Time/Ozds.Time.csproj" />
    <ProjectReference Include="../../src/Ozds.Assets/Ozds.Assets.csproj" />
    <ProjectReference Include="../../src/Ozds.Data/Ozds.Data.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Testcontainers" />
  </ItemGroup>

</Project>
